language: csharp
solution: DDDTest.sln
before_install:
  - sudo apt-get install nunit-console
install:
  - nuget restore DDDTest.sln
script:
  - xbuild /p:Configuration=Release DDDTest.sln /p:TargetFrameworkVersion="v4.5"
  - nunit-console DDDTest.UnitTests/bin/Release/DDDTest.UnitTests.dll

