language: csharp
solution: DDDTest.sln
install:
  - nuget restore DDDTest.sln
  - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DDDTest.sln /p:TargetFrameworkVersion="v4.5"
  - mono ./testrunner/NUnit.Runners.3.2.1/tools/nunit-console.exe ./DDDTest.UnitTests/bin/Release/DDDTest.UnitTests.dll
